import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import TopBar from '@/components/shared/topBar'
import LeftBar from '@/components/shared/leftBar'
import RightBar from '@/components/shared/rightBar'
import ButtomBar from '@/components/shared/buttomBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
       <body>
        <TopBar />
          <main className='flex'>
            <LeftBar />
            <section className='main-container'>
              <div className='w-full max-w-4xl'>
                {children}
              </div>
            </section>
            <RightBar />
          </main>
        <ButtomBar />
       </body>
      </html>
    </ClerkProvider>
  )
}
